# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('writer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=500)),
                ('pub_date', models.DateField()),
            ],
            options={
                'ordering': ('headline',),
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magazine_name', models.CharField(max_length=50)),
                ('arts', models.ManyToManyField(to='Articles.Article', verbose_name='Article')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writer.Publisher')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('editors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writer.Editor')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.AddField(
            model_name='magazine',
            name='pubs',
            field=models.ManyToManyField(to='Articles.Publication', verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='article',
            name='publications',
            field=models.ManyToManyField(to='Articles.Publication', verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='article',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writer.Reporter'),
        ),
    ]
